### ISSUE TITLE
Export-MRNGConnectionFile throws error: Unable to find type [mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26]

### ISSUE THREAD

**Issue by Stephanevg** [realslacker/PSmRemoteNG#1]
Hi,

We have been chatting on Reddit

```powershell
import-module "D:\plop\psmRemoteNG\psmRemoteNG.psd1" -force
$VerbosePreference = "continue"
$ExportPath = "D:\plop\mremote.xml"
$csv = import-csv "D:\plop\ServerData.csv"
$RootNode = New-MRNGRootNode -EncryptionKey ( ConvertTo-SecureString -String 'mR3m' -AsPlainText -Force )

$AllTenants = $csv | Group TenantID
$InheritanceSplat = @{}
$IsInherited = New-MRNGInheritanceConfiguration -EverythingInherited

Foreach($Tenant in $AllTenants){

    
    $TenantContainer = New-MRNGContainer -Name $Tenant.Name -Parent $RootNode -Inheritance $IsInherited
    
    Foreach($Machine in $Tenant.Group){
        
        $ServerConnection = New-MRNGConnection -Name $Machine.MachineName -Hostname $Machine.translatedIP -Description $Machine.ComputerName -Parent $TenantContainer -Inheritance $IsInherited
        
    }
}

Export-MRNGConnectionFile -RootNode $RootNode -Path $ExportPath -SortConnections
```

This is the error I get

![image](https://user-images.githubusercontent.com/6302961/65359695-9d133000-dbfd-11e9-8cf3-0cdcebcefff1.png)

When seting a breakpoint and looking into the code, it really fails on line 488of the psm1.

It seems like it cannot find: ```[mRemoteNG.Config.Serializers.Xml.XmlConnectionNodeSerializer26]```

Any idea?

**Comment by realslacker** [comment]
What version of mRemoteNG do you have installed?

**Comment by Stephanevg** [comment]
@realslacker 
![image](https://user-images.githubusercontent.com/6302961/65360209-46a6f100-dbff-11e9-8094-6f4d34673165.png)

**Comment by realslacker** [comment]
Ah, I think they changed the way connections are serialized in 1.76, which is actually why I wrote this module... the example code for PowerShell was broken in the latest version and I had a need to export a connection file.

Try the latest version of mRemoteNG and see if the error goes away.

**Comment by realslacker** [comment]
Specifically I'm running 1.76.20.24615.

If that's the case we could potentially try to detect the version running and look back for the "old" way to serialize connection files.

**Comment by Stephanevg** [comment]
Yeah, that would be a great addition I think. This software is installed ona few servers of mine, and updating them will be a bit of a challenge for me.

I can try it out locally on the latest version if you want

**Comment by Stephanevg** [comment]
seems like it is related to this change -> https://github.com/mRemoteNG/mRemoteNG/issues/1401

**Comment by Stephanevg** [comment]
So I confirm @realslacker The same code works with 1.76.20
That retrocompatible fix there would be perfect indeed!

**Comment by realslacker** [comment]
@Stephanevg can you please test [compat-v1.75](/realslacker/PSmRemoteNG/tree/compat-v1.75)

**Comment by Stephanevg** [comment]
Ok @realslacker I'll try it as soon as I have minute
