### ISSUE TITLE
Does not work well with 1.77 

### ISSUE THREAD

**Issue by greedj** [realslacker/PSmRemoteNG#3]
When importing an existing 1.77 confCons.xml, then creating a new root folder and folders/leafs under the new folder to the object, and then re-saving it; The inheritance on any pre-existing folders and objects off the root get messed up. The new folder and sub objects seem ok.
This does not happen in 1.76 and it might be because they added new object properties in 1.77.

**Comment by realslacker** [comment]
There are some significant differences in v1.77, for now since v1.76.20 is the stable branch I'm not going try to code compatibility.
